edition = "2021"
fn_params_layout = "Compressed"
hard_tabs = false
match_block_trailing_comma = true
max_width = 90
merge_derives = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true