[package]
name = "media_fetch_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5.0"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
dotenvy = "0.15.7"
thiserror = "1.0.61"
rust-i18n = "3.0.1"
strum = "0.26"
strum_macros = "0.26"